Мелкое исправление логики в импорте LSS
TTG-Club/ttg-club-backend pull request #122
Opened 2024-03-29 20:21 UTC by ProtectorRTD

1) Исправление пути в контроллере

2) Обновление сервиса. Так как версия фаундри не используется по назначению там.

2024-03-29 23:44 UTC, svifty7 requested changes

2024-03-29 23:44 UTC, svifty7 commented on src/main/java/club/dnd5/portal/controller/api/LssApiController.java
> +	@GetMapping(value = "/spell/{spellId}", produces = "application/json")
на 11 строке еще слэш забыл

2024-03-30 10:52 UTC, ProtectorRTD commented on src/main/java/club/dnd5/portal/controller/api/LssApiController.java
> +	@GetMapping(value = "/spell/{spellId}", produces = "application/json")
Исправлено

2024-04-01 19:51 UTC, svifty7 approved these changes

2024-04-03 06:12 UTC, Magistrus approved these changes

2024-04-03 06:24 UTC, merged