Dev bugfix/bestiary spells
TTG-Club/ttg-club-backend pull request #90
Opened 2023-10-13 11:00 UTC by ProtectorRTD

- Добавление контроллера Parser, который позволяет записывать JSON в базу данных и автоматически настраивает PK.
- Изменение и расширение интерфейсов в Entity Spell и Creature для упрощения будущего редактирования сервиса. Это позволит добавлять поля через интерфейс, которые будут необходимы, в случае если придется добавлять или изменять другие поля помимо description.
- Введение в действие сервиса JsonStorageService и JsonStorageRepository.
- Добавление методов в SpellApiController и BestiaryApiController, которые предоставляют JSON-файлы, готовые для экспорта на сайт Foundry 11. _Старый метод для версии Foundry 10 остался в работе._
- Добавление сущности JsonStorage и составного ключа для этой сущности.

2023-10-13 11:10 UTC, svifty7 requested changes

2023-10-13 11:10 UTC, svifty7 commented on .gitignore
> +/src/main/resources/application-dev.properties
это не надо) у нас в гите профили для дева и прода

2023-10-13 11:10 UTC, svifty7 commented on src/main/java/club/dnd5/portal/dto/fvtt/export/spell/Fspell.java
> +	private String usesMax;
разные отступы

2023-10-13 11:10 UTC, svifty7 commented on src/main/java/club/dnd5/portal/dto/fvtt/export/system/FSystemSpell.java
> +	private FScaling scaling; //++
комменты непонятные) лучше описать, если это нужно

2023-10-13 11:10 UTC, svifty7 commented on src/main/java/club/dnd5/portal/model/splells/Spell.java
> +
гит помнит, лучше удалять, если не нужно

2023-10-13 11:10 UTC, svifty7 commented on src/main/java/club/dnd5/portal/service/JsonStorageService.java
> +
лишние отступы тоже не стоит)

2023-10-13 11:10 UTC, svifty7 commented on src/main/java/club/dnd5/portal/controller/api/SpellApiController.java
> -		    content = @Content) })
по отступам стараться меньше изменений делать

2023-10-13 16:36 UTC, Magistrus approved these changes

2023-10-14 20:48 UTC, Magistrus approved these changes

2023-10-14 20:48 UTC, Magistrus commented on src/main/java/club/dnd5/portal/controller/api/ParserController.java
> +public class ParserController {
Как то название не говорить для чего он. 
Может JsonParseController

2023-10-14 20:48 UTC, Magistrus commented on src/main/java/club/dnd5/portal/service/JsonStorageServiceImpl.java
> +public class JsonStorageServiceImpl implements JsonStorageService {
а транзакционность не стоит сюда добавить?

2023-10-14 20:48 UTC, Magistrus commented on src/main/java/club/dnd5/portal/controller/api/ParserController.java
> +	public void importCreature(@RequestBody List<JsonNode> request) {
Должно работать только для роли ADMIN

2023-10-14 20:48 UTC, Magistrus commented on src/main/java/club/dnd5/portal/controller/api/ParserController.java
> +	public void importSpells(@RequestBody List<JsonNode> request) {
Должно работать только для роли ADMIN

2023-10-17 07:56 UTC, svifty7 approved these changes

2023-10-18 06:47 UTC, merged