Added a new Entity / API (Configuration)
TTG-Club/ttg-club-backend pull request #97
Opened 2023-10-31 15:24 UTC by ProtectorRTD

- SiteConfiguration: This class specifies the configuration parameters and their corresponding values.

- SiteConfigurationApiController: This controller is responsible for retrieving specific configuration(s) or all configurations as needed.

2023-10-31 22:08 UTC, svifty7 approved these changes

2023-11-01 14:12 UTC, Magistrus approved these changes

2023-11-07 11:01 UTC, Magistrus requested changes

2023-11-07 16:24 UTC, ProtectorRTD commented on src/main/java/club/dnd5/portal/controller/api/SiteConfigurationApiController.java
> +		siteConfigurationRepository.findAll().forEach(siteConfigurations::add);
Согласен, переделал

2023-11-07 16:24 UTC, ProtectorRTD commented on src/main/java/club/dnd5/portal/controller/api/SiteConfigurationApiController.java
> +	public ResponseEntity<List<SiteConfiguration>> getConfigByKeys(@RequestParam List<String> keys) {
Переделал

2023-11-10 12:43 UTC, Magistrus approved these changes

2023-11-12 12:22 UTC, merged