Ttg 32  feature/armor filter
TTG-Club/ttg-club-backend pull request #99
Opened 2023-11-09 19:14 UTC by ProtectorRTD

2023-11-10 12:35 UTC, Magistrus requested changes

2023-11-10 12:35 UTC, Magistrus commented on src/main/java/club/dnd5/portal/controller/api/item/ArmorApiController.java
> +			.collect(Collectors.toList());
проще было бы просто прописать варианты, но пусть будет так

2023-11-10 12:35 UTC, Magistrus commented on src/main/java/club/dnd5/portal/dto/api/item/ArmorFilter.java
> +	private List<Integer> typeArmor;
тут нужно Enum использовать
ты отдаешь же название enum в качестве фильтра

2023-11-10 12:35 UTC, Magistrus commented on src/main/java/club/dnd5/portal/controller/api/item/ArmorApiController.java
> +		List<FilterValueApi> disadvantageValues = new ArrayList<>();
используй capacity 
new ArrayList<>(2);

2023-11-13 09:31 UTC, ProtectorRTD commented on src/main/java/club/dnd5/portal/controller/api/item/ArmorApiController.java
> +		List<FilterValueApi> disadvantageValues = new ArrayList<>();
Согласен, исправил

2023-11-13 09:32 UTC, ProtectorRTD commented on src/main/java/club/dnd5/portal/dto/api/item/ArmorFilter.java
> +	private List<Integer> typeArmor;
Переделал

2023-11-13 09:42 UTC, Magistrus approved these changes

2023-11-13 09:44 UTC, merged